// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlymsklpbvvlltthorli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpseW1za2xwYnZ2bGx0dGhvcmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTYyMDgsImV4cCI6MjA1NTUzMjIwOH0.KcA2QpPwZJic0vWeuNeL3pWwr23uXaOrg3EECnPS0Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);